package net.castleadventure.ospgarath.model.characterClass;

public enum ClassDescription {

    CHAMPION("Champion", "Champions are gifted warriors whose successes in combat have brought them fame and renown. Though many serve as guards or knights to greater lords, some are merely gifted combatants who crave the thrill of the fight. In battle, they often seek the largest and most dangerous of enemies and prefer to tackle a fight head on. The champion is a skilled melee fighter and makes use of any number of different weapons and strategies."),
    BARBARIAN("Barbarian", "Brutal, dangerous, fearless, and often misunderstood, barbarians are the warrior classes that roam the wildlands and wastes beyond the realms of civilized folk. Though their ways and methods are often primitive, their ferocity in battle is undeniable. Barbarians often prefer to fight with weapons that let them make use of their vast strength and quickness, while traditionally eschewing armor in place of greater mobility in battle."),
    OUTRIDER("Outrider", "Acting as front line advance scouts for military units, raiding parties, and traveling caravans, the outrider is a skilled fighter when sitting astride his faithful animal mount. The outrider makes use of his animal mount’s strength and speed to make powerful attacks and ride down enemies on the battlefield."),
    SKINCHANGER("Skinchanger", "Reclusive and mysterious, skinchangers normally live an isolated existence away from the laws and kingdoms of other beings. They prefer instead the company of animals, and have even honed their unique skills to be able to take the form of an animal in combat.   Because of this, they prefer light equipment and armor that does not encumber them. Skinchangers are quick to anger and aggression, but can be loyal friends if their trust is earned."),
    WEAPON_MASTER("Weapon Master", "Rather than committing themselves to a cause or swearing to a sovereign lord, weapon masters are concerned only with the study of their craft. Working tirelessly, they hone their skills with one specific weapon and neglect training in most other aspects. This makes them gifted fighters, if somewhat overly reliant on their weapon of choice."),
    PALADIN("Paladin", "Among every race of folk there are those who devote themselves to the cause of a higher power or ideal.  Sometimes these individuals serve as guardians of their homeland, while others take to adventuring to further their cause. The paladin is a stalwart defender of what he believes to be right and true, and generally marches into battle heavily equipped with armor and weapons. In combat, paladins’ convictions add to their defense and skill with a shield."),
    RANGER("Ranger", "Traveling to some of the deepest reaches of the uncharted frontier, rangers spend their days in the wildlands. Yet unlike barbarians or skinchangers, they do so at the benefit of the kingdoms of free folk. Rangers guard the borders of the lands they love and journey to deal with threats that common folk never see. In battle, they are effective with both ranged and melee attacks, and capable of fighting simultaneously with two weapons."),
    BRAWLER("Brawler", "Some warriors are compelled to fight to defend that which they hold dear. Others enjoy fighting for the sake of the fight itself. Such is the case with the brawler, who sees the thrill of fighting as tantamount to the pursuit of happiness. Brawlers make use of their quickness and strength to engage enemies, and many choose to fight unarmed in order to utilize their unique skills and grappling powers."),
    BOWMAN("Bowman", "There are creatures of all races that possess a special connection with the bow. These individuals typically reject the use of other weapons in favor of furthering their archery skills. In combat, the bowman generally prefers to remain on the outskirts of the battle to attack enemies from a distance, and generally avoids wearing armor to ensure that his precision is not compromised."),
    BURGLAR("Burglar", "Burglars make their living relying on stealth and agility to succeed where others cannot. Though many choose to live outside the boundaries of the law, some devote their skills to the causes of justice and lend their talents to assisting the forces of good. In battle, burglars prefer to avoid direct melee combat if possible and attack their enemies when their defenses are lowered.  Burglars typically avoid armor and shields to keep their focus on moving silently and efficiently through the field of battle."),
    HUNTER("Hunter", "The hunter is a respected position amongst the free peoples. Responsible for helping protect the civilizations that dot the land, hunters are trained to track and kill with a variety of ranged and melee weapons. Since they typically deal with a type of threat native to their homeland, each hunter also has a specific type of enemy against which it has learned to specialize and prevail in combat."),
    ASSASSIN("Assassin", "As unscrupulous as they are deadly, assassins are those denizens of the free folk willing to make a profession of taking lives. While some pursue this path as a means of financial gain or out of loyalty to a cause, some take it up for no other reason than that they are drawn to the craft. In any case, assassins make use of calculated attacks that hinder their enemies or inflict them with poisons, and  on the battlefield take pride in silently bringing down the strongest of enemy warriors."),
    MAGE("Mage", "Though they may appear to be like most other warriors, mages are trained specifically for the purpose of checking and defeating spell-casters. While they are trained to exert both mental and physical abilities, they reject spell-casting in favor of attacks that are infused with great power. In battle they often choose to equip themselves with heavy armor and weapons, yet their very specialized training puts them at somewhat of a disadvantage when fighting other melee combat classes."),
    NECROMANCER("Necromancer", "Usually hailing from lands far in the east, necromancers are a mysterious group of adventurers. Many see them as purely evil bastions of death and suffering, while others recognize in their strange arts a connection to a powerful and possibly misunderstood force. Yet all seem to treat them with some respect, for necromancers are spell-casters and formidable enemies. On the battlefield, they often prefer to avoid direct fights, but will make use of their strength to inflict melee attacks that weaken or cripple their enemies."),
    SORCERER("Sorcerer", "Among the older races of the free folk, there are those born with a natural connection to the unseen powers that unite and shape the world. These creatures do not study or train their abilities, their powers simply grow with them in strength and potency. With their unique talents, sorcerers do not use weapons, but they can control and dominate their enemies and inflict their will from a distance."),
    ALCHEMIST("Alchemist", "Combining scientific research with the power of studied spells, alchemists have long been able to carefully bottle potions of the mystic arts and make them available to those that can afford their services. Though their order has dwindled significantly in recent generations, those that still operate are often easily recognizable by their hair and sometimes skin, which has taken on an azure hue. In battle, they use their blends of ingredients and spell power to aid their teammates and damage enemies. However, they generally avoid direct combat and prefer to orchestrate from a distance."),
    CONJURER("Conjurer", "Conjurers develop their powers through careful research, and study spells in the tongues of all free folks.  Using these powers, conjurers make powerful attacks, block the abilities of others, and mire their enemies in painful conditions. Conjurers are nearly always seen wielding a staff, as they are reliant on them to focus their powers.  Many rely on the assistance of woodland animals, having learned to converse with them."),
    HEALER("Healer", "While there are a number of adventuring classes capable of providing health and assistance to those in need, the healer devotes their life fully to the aid of others. Generally putting almost no thought or training into melee fighting, healers instead excel at helping teammates regain endurance, overcome detrimental conditions, and sometimes even cheat death. In battle, healers move fearlessly through the ranks of the wounded to offer support, but rarely choose to engage in direct combat themselves."),
    CAPTAIN("Captain", "The captain is a born leader, raised to guide his compatriots on the battlefield. Using his knowledge of military strategy, the captain can counter the attacks of his enemies, while offering powerful bonuses to his teammates. In battle, the captain is a skilled melee fighter and excels in situations where he can heroically defend an ally or crush weaker enemies."),
    MARINER("Mariner", "Mariners are sailors, corsairs, and journeymen who long ago surrendered their hearts to the call of the sea. They are discordant, unpredictable, and deceptive, and perhaps because of this they wreak havoc on the plans of commanders and field marshals who pride themselves on disciplined strategy. Each mariner deems himself his own personal commander, and in battle uses his leadership skills to not only augment his own abilities, but to also hamper the powers of his enemies."),
    SOVEREIGN("Sovereign", "While it is not common for a lord or lady to take to adventuring, it is not totally unheard of either. In some instances, this is done out of some urgent errand of necessity, yet at other times it is simply the case of a ruler growing restless and uneasy with a life of opulence. Some rulers are gifted fighters, while others rely on their intelligence, yet all are skilled tacticians that inspire and benefit their allies and followers in combat."),
    SHEPHERD("Shepherd", "Whether tending to animal husbandry or living out among the herd, shepherds have a special connection to the beasts of the world.  Shepherds make use of animal companions and loyal pets, but can exert influence over even the most vicious and loathsome of beasts. In battle, shepherds prefer to either fight from a distance or rely on help from their animal companions, and while many of these animals are not skilled fighters, most have found ways to benefit the shepherd in some capacity."),
    SCHOLAR("Scholar", "While most generally prefer to pursue their studies from the safety of archived library collections, there are some scholars who take to a life of adventuring to further their work. Though they may not be the most talented warriors, scholars nevertheless may be invaluable to their teammates, as their years of learning often prove beneficial when confronting the challenges of new enemies or otherwise forgotten locations."),
    BARD("Bard", "Myriad adventurers can swing a sword or lead a charge, but it is the bard that truly brings each of them glory. Always quick to share a song or limerick with an eager audience, the bard sees it his duty to spin tales of great valor and worthy deeds. In doing so, bards are able to tap into the fundamental powers that shape probability and luck, and greatly affect them to the aid of their teammates. In battle, the bard often ignores fighting altogether in favor of issuing powerful commands by way of song.");

    private String className;
    private String classDescription;

    ClassDescription(String className, String classDescription) {
        this.className = className;
        this.classDescription = classDescription;
    }

    public static String getClassDescription(String className) {
        for(ClassDescription description : ClassDescription.values()) {
            if (description.className.equalsIgnoreCase(className)) {
                return description.classDescription;
            }
        }
        throw new IllegalArgumentException();
    }
}
