package net.castleadventure.ospgarath.model.characterClass;

import net.castleadventure.ospgarath.game.Dice;

public enum NPCName {
    Meri,
    Ferthgrim,
    Fastphia,
    Rencen,
    Chrisbri,
    Niferum,
    Ryven,
    Fortinhelm,
    Tonba,
    Ferthson,
    Namark,
    Ricand,
    Adelbras,
    Niken,
    Ferumegar,
    Adeled,
    Chardven,
    Toton,
    An,
    Seanegar,
    Halacar,
    Chellacar,
    Wulfcuth,
    Betard,
    Sharo,
    Naskev,
    Seanca,
    Kenisum,
    Forthfer,
    Lafmuel,
    Wisetoven,
    Ethelmuel,
    Bridic,
    Thorphie,
    Soichael,
    Kesan,
    Waldcia,
    Sephbeorn,
    Hereni,
    Pherthy,
    Pado,
    Uvidry,
    Grimlin,
    Brytri,
    Nielmuel,
    Ricjo,
    Gormape,
    Isumarto,
    Leofjeff,
    Donthae,
    Eliord,
    Phercan,
    Samwil,
    Do,
    Egarlinro,
    Riaever,
    Nassa,
    Werdbeorth,
    Ly,
    Ardha;

    public static NPCName getRandom() {
        Integer index = Dice.dynamic(NPCName.values().length);
        return NPCName.values()[index-1];
    }
}
